items:
- cost: 消耗
- point: 积分
- exchange: 兑换物
pools:
- main:
  - probability: 0.5
    actions: point += 1
  - probability: 0.5
    actions: point += 2
every_draw:
- cost += 1
rules:
- exchange_points:
    mode: repeat
    condition:
      check: point >= 5
      actions:
      - point -= 5
      - exchange += 1
initial:
- change main
schema_version: 1
