id: quanjiahezi_maniandaji
name: test
description: test
metrics: [draw]
terminations:
- file: termination_mouzhugeliang.yaml
  name: termination_mouzhugeliang
- file: termination_quan1.yaml
  name: termination_quan1
- file: termination_shenjiangwei.yaml
  name: termination_shenjiangwei
metadata:
  name: test
  source: https://www.sanguosha.cn/pc/news-detail-2256.html
  game: sanguoshayidonban
  time: '2026_4_24'
  cost_id: maniandaji
  cost_name: 马年大吉
  amount: 1
  per_cost_to_rmb: 2
