schema_version: 2
items:
  - draw_count: 抽数
  - target
  - coin
pools:
  - main:
      - probability: 0.05
        actions: target += 1
      - probability: 0.95
        actions: coin += 1
initial:
  - change main
every_draw:
  - draw_count += 1
