retained_items:
- yao_daergouzhimeng: 1
- sanliouduihuanbi: 952
termination_rule:
  cases:
  - conditions:
    - yao_daergouzhimeng >= 1
    - sanliouduihuanbi >= 454
    reason: 抽中皮肤并兑换其余礼包
  - conditions: sanliouduihuanbi >= 952
    reason: 兑换币兑换
