retained_items:
- yao_daergouzhimeng: 1
- sanliouduihuanbi: 498
termination_rule:
  cases:
  - conditions: yao_daergouzhimeng >= 1
    reason: 抽中皮肤
  - conditions: sanliouduihuanbi >= 498
    reason: 兑换币兑换
