retained_items:
- mianhuatangjuhuitianmu: 1
- sanliouduihuanbi: 428
termination_rule:
  cases:
  - conditions: mianhuatangjuhuitianmu >= 1
    reason: 抽中天幕
  - conditions: sanliouduihuanbi >= 428
    reason: 兑换币兑换
