retained_items:
  - mianhuatangjuhuitianmu: 1
  - sanliouduihuanbi: 428

termination_rule:
  conditions:
    op: OR
    conditions:
      - "mianhuatangjuhuitianmu >= 1"
      - "sanliouduihuanbi >= 428"
  reason: 抽中天幕或兑换币兑换
