meta_data:
  name: sunwukong_wuxiang
  source: https://pvp.qq.com/web201706/newsdetail.shtml?tid=791287
  game: 王者荣耀
  time: '2026_1_1'
  cost_id: wuxiang_coin
  cost_name: 无相祈愿币
  amount: 10
  per_cost_to_rmb: 1
items:
- wuxiang_point: 无相积分
- random_limited_skin: 随机限定皮肤礼
- random_legendary_skin: 随机传说皮肤
- random_skin: 随机皮肤礼
- skin_fragment8: 皮肤碎片8
- xiaozhoujimeng2: 小舟寄梦2
- sunwukong_wuxiang: 孙悟空_无相
- yao_zhenwohezi: 瑶_真我赫兹
- zhenji_xuejingqiyu: 甄姬_雪境奇遇
- xuejingqiyuquanpingtianmu: 雪境奇遇全屏天幕
- xiaoqiao_shanhailinlangsheng: 小乔_山海琳琅生
- zhaoyun_longdan: 赵云_龙胆
- daji_reqingsangba: 妲己_热情桑巴
- epic_skin: 史诗皮肤
- brave_skin: 勇者皮肤
- companion_skin: 伴生皮肤
- draw_count: Draw count
pools:
- begin_pool:
  - probability: 0.004
    actions: random_limited_skin += 1
  - probability: 0.005
    actions: random_legendary_skin += 1
  - probability: 0.135
    actions: random_skin += 1
  - probability: 0.008
    actions: wuxiang_point += 68
  - probability: 0.04
    actions: wuxiang_point += 28
  - probability: 0.237
    actions: wuxiang_point += 18
  - probability: 0.3
    actions: wuxiang_point += 8
  - probability: 0.15
    actions: skin_fragment8 += 1
  - probability: 0.121
    actions: xiaozhoujimeng2 += 1
- random_limited_skin_pool:
  - probability: 0.0034
    actions: sunwukong_wuxiang += 1
  - probability: 0.0033
    actions: yao_zhenwohezi += 1
  - probability: 0.0033
    actions: zhenji_xuejingqiyu += 1
  - probability: 0.01
    actions: xuejingqiyuquanpingtianmu += 1
  - probability: 0.32
    actions: xiaoqiao_shanhailinlangsheng += 1
  - probability: 0.33
    actions: zhaoyun_longdan += 1
  - probability: 0.33
    actions: daji_reqingsangba += 1
- random_skin_pool:
  - probability: 0.1
    actions: epic_skin += 1
  - probability: 0.3
    actions: brave_skin += 1
  - probability: 0.6
    actions: companion_skin += 1
every_draw:
- draw_count += 1
rules:
- name: 5draw
  mode: once
  condition:
    check: draw_count >= 5
    actions:
    - random_skin += 1
- name: 10draw
  mode: once
  condition:
    check: draw_count >= 10
    actions:
    - random_skin += 1
- name: 25draw
  mode: once
  condition:
    check: draw_count >= 25
    actions:
    - random_skin += 1
- name: 40draw
  mode: once
  condition:
    check: draw_count >= 40
    actions:
    - wuxiang_point += 288
- name: 45draw
  mode: once
  condition:
    check: draw_count >= 45
    actions:
    - random_skin += 1
- name: 50draw
  mode: once
  condition:
    check: draw_count >= 50
    actions:
    - random_skin += 1
- name: 65draw
  mode: once
  condition:
    check: draw_count >= 65
    actions:
    - random_skin += 1
- name: 80draw
  mode: once
  condition:
    check: draw_count >= 80
    actions:
    - wuxiang_point += 288
- name: 85draw
  mode: once
  condition:
    check: draw_count >= 85
    actions:
    - random_skin += 1
- name: 90draw
  mode: once
  condition:
    check: draw_count >= 90
    actions:
    - random_skin += 1
- name: 105draw
  mode: once
  condition:
    check: draw_count >= 105
    actions:
    - random_skin += 1
- name: 120draw
  mode: once
  condition:
    check: draw_count >= 120
    actions:
    - wuxiang_point += 288
item_resolve:
- item: random_limited_skin
  retain: 0
  actions:
  - random_limited_skin -= 1
  - draw random_limited_skin_pool
- item: random_legendary_skin
  retain: 0
  actions:
  - random_legendary_skin -= 1
  - wuxiang_point += 120
- item: random_skin
  retain: 0
  actions:
  - random_skin -= 1
  - draw random_skin_pool
- item: skin_fragment8
  retain: 0
  actions:
  - skin_fragment8 -= 1
  - wuxiang_point += 5
- item: xiaozhoujimeng2
  retain: 0
  actions:
  - xiaozhoujimeng2 -= 1
  - wuxiang_point += 5
- item: sunwukong_wuxiang
  retain: 0
  actions:
  - sunwukong_wuxiang -= 1
  - wuxiang_point += 288
- item: yao_zhenwohezi
  retain: 0
  actions:
  - yao_zhenwohezi -= 1
  - wuxiang_point += 288
- item: zhenji_xuejingqiyu
  retain: 0
  actions:
  - zhenji_xuejingqiyu -= 1
  - wuxiang_point += 288
- item: xuejingqiyuquanpingtianmu
  retain: 0
  actions:
  - xuejingqiyuquanpingtianmu -= 1
  - wuxiang_point += 288
- item: xiaoqiao_shanhailinlangsheng
  retain: 0
  actions:
  - xiaoqiao_shanhailinlangsheng -= 1
  - wuxiang_point += 288
- item: zhaoyun_longdan
  retain: 0
  actions:
  - zhaoyun_longdan -= 1
  - wuxiang_point += 288
- item: daji_reqingsangba
  retain: 0
  actions:
  - daji_reqingsangba -= 1
  - wuxiang_point += 288
- item: epic_skin
  retain: 0
  actions:
  - epic_skin -= 1
  - wuxiang_point += 60
- item: brave_skin
  retain: 0
  actions:
  - brave_skin -= 1
  - wuxiang_point += 40
- item: companion_skin
  retain: 0
  actions:
  - companion_skin -= 1
  - wuxiang_point += 20
initial:
- change begin_pool
