schema_version: 2
items:
  - draw_count: 抽数
  - target
  - token
pools:
  - main:
      - probability: 0.1
        actions: target += 1
      - probability: 0.9
        actions: token += 1
initial:
  - change main
every_draw:
  - draw_count += 1
