id: banjiahezi_xiadanzhonhun
name: test
description: test
metrics: [draw]
terminations:
- file: termination_quan1.yaml
  name: termination_quan1
- file: termination_shiweiyan.yaml
  name: termination_shiweiyan
metadata:
  name: test
  source: https://www.sanguosha.cn/pc/news-detail-2100.html
  game: sanguoshayidonban
  time: '2026_4_25'
  cost_id: xiaddanzhonhun
  cost_name: 侠胆忠魂
  amount: 1
  per_cost_to_rmb: 1
