items:
  - draw_count: 抽数
  - target: 目标
  - miss: 未命中
pools:
  - main:
      - probability: 0.1
        actions: target += 1
      - probability: 0.9
        actions: miss += 1
every_draw:
  - draw_count += 1
initial:
  - change main
